/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#f8f2fa",
        "on-secondary-fixed": "#1f1635",
        "on-error-container": "#93000a",
        "on-secondary-container": "#645a7d",
        "outline": "#7a7582",
        "surface": "#fdf7ff",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed-variant": "#594400",
        "surface-container-high": "#ece6ee",
        "surface-dim": "#ded8e0",
        "on-primary-container": "#e0d2ff",
        "error": "#ba1a1a",
        "surface-tint": "#6750a4",
        "tertiary": "#765b00",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#f5eff7",
        "on-tertiary-fixed": "#241a00",
        "on-surface-variant": "#494551",
        "inverse-primary": "#cfbcff",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#e7c365",
        "error-container": "#ffdad6",
        "on-secondary-fixed-variant": "#4b4263",
        "primary": "#4f378a",
        "primary-fixed-dim": "#cfbcff",
        "on-primary-fixed-variant": "#4f378a",
        "surface-variant": "#e6e0e9",
        "inverse-surface": "#322f35",
        "tertiary-container": "#c9a74d",
        "primary-fixed": "#e9ddff",
        "on-primary-fixed": "#22005d",
        "surface-bright": "#fdf7ff",
        "tertiary-fixed": "#ffdf93",
        "secondary": "#63597c",
        "secondary-fixed-dim": "#cdc0e9",
        "on-surface": "#1d1b20",
        "secondary-container": "#e1d4fd",
        "surface-container": "#f2ecf4",
        "on-error": "#ffffff",
        "on-tertiary-container": "#503d00",
        "on-background": "#1d1b20",
        "primary-container": "#6750a4",
        "on-primary": "#ffffff",
        "outline-variant": "#cbc4d2",
        "surface-container-highest": "#e6e0e9",
        "secondary-fixed": "#e9ddff",
        "background": "#fdf7ff"
      },
      borderRadius: {
        "DEFAULT": "0px",
        "lg": "0px",
        "xl": "0px",
        "full": "0px"
      },
      fontFamily: {
        headline: ["Public Sans", "sans-serif"],
        display: ["Public Sans", "sans-serif"],
        body: ["Public Sans", "sans-serif"],
        label: ["Public Sans", "sans-serif"],
        mono: ["Space Mono", "Courier New", "monospace"]
      }
    },
  },
  plugins: [],
}
